"""add_user_profile_fields

Revision ID: 5a26662ec472
Revises: 
Create Date: 2026-03-28 22:36:58.393744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '5a26662ec472'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fitness_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('daily_calories_target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goal_summary')
        batch_op.drop_column('daily_calories_target')
        batch_op.drop_column('fitness_goal')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')

    # ### end Alembic commands ###
