"""add_details_json_to_workout

Revision ID: fffb69ef0a1c
Revises: 5a26662ec472
Create Date: 2026-03-29 11:52:20.694335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'fffb69ef0a1c'
down_revision: Union[str, None] = '5a26662ec472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutsession', schema=None) as batch_op:
        batch_op.drop_column('details_json')

    # ### end Alembic commands ###
